name: app_config
description: App configuration flutter 
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  singleton: ^0.0.3-nullsafety
  logger: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true